import 'package:http/http.dart' as http;
import 'dart:convert';

class Weather {
  String? dt;
  Mains mains;

  Weather({this.dt, required this.mains});

  factory Weather.fromJson(Map<String, dynamic> json) {
    return Weather(dt: json['dt_txt'], mains: Mains.fromJson(json['main']));
  }
}

class Mains {
  double? temp;

  Mains({this.temp});
  factory Mains.fromJson(Map<String, dynamic> json) {
    return Mains(temp: json['temp']);
  }
}

Future<Weather?> apiConnect() async {
  // final response = await http.get(Uri.parse(
  //     "api.openweathermap.org/data/2.5/forecast?lat=-6.200000&lon=106.816666&exclude=daily&units=metric&appid=49e5853edeb3e252fcd4177d15aca5ad&cnt=1"));
  // if (response.statusCode == 200) {
  //   final responseJson = json.decode(response.body);
  //   final autogenerated = Weather.fromJson(responseJson);
  //   return autogenerated;
  // } else {
  //   throw Exception('Unexpected Error Occured!');
  // }
  try {
    var url =
        'https://api.openweathermap.org/data/2.5/forecast?lat=-6.200000&lon=106.816666&exclude=daily&units=metric&appid=49e5853edeb3e252fcd4177d15aca5ad';

    var apiResult = await http.get(Uri.parse(url));
    var jsonObject = jsonDecode(apiResult.body);
    var userData = (jsonObject as Map<String, Map<String, dynamic>>);

    return Weather.fromJson(userData);
  } catch (e) {
    print(e);
  }
}
